services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - menedez_data:/app/data
    restart: always

volumes:
  menedez_data:
    driver: local
